### ISSUE TITLE
Get track info in AppleScript

### ISSUE THREAD

**Issue by nerdpad** [beardedspice/beardedspice#516] opened 2016-11-28 20:15 UTC
I am currently using an applescript to display current playing track from Spotify in terminal.

What is the equivalent in BeardedSpice?

```applescript
else if application "Spotify" is running then
  tell application "Spotify"
    set theName to name of the current track
    set theArtist to artist of the current track
    set theAlbum to album of the current track
    set theUrl to spotify url of the current track
    try
      return "♫  " & theName & " - " & theArtist
    on error err
    end try
  end tell
if application "BeardedSpice" is running then
  tell application "BeardedSpice"
    set theName to name of the current track (* Error here: Expected end of line but found identifier *)
    set theArtist to artist of the current track
    try
      return "♫  " & theName & " - " & theArtist
    on error err
    end try
  end tell
end if
```

Any help is appreciated.

### Solved (Working Script)

Just for future reference for anyone who wants a working script. Thank you everyone for the help

```applescript
(* Get the current song from iTunes or Spotify or BeardedSpice *)
if application "iTunes" is running then
  tell application "iTunes"
    if exists current track then
      set theName to the name of the current track
      set theArtist to the artist of the current track
      try
        return "♫  " & theName & " - " & theArtist
      on error err
      end try
    end if
  end tell
else if application "Spotify" is running then
  tell application "Spotify"
    set theName to name of the current track
    set theArtist to artist of the current track
    set theAlbum to album of the current track
    set theUrl to spotify url of the current track
    try
      return "♫  " & theName & " - " & theArtist
    on error err
    end try
  end tell
else if application "BeardedSpice" is running then
  tell application "BeardedSpice"
    set title to full title of application "BeardedSpice"

    if title is not missing value and title does not starts with "Your stream on" then
      try
        return "♫  " & title
      on error err
      end try
    end if
  end tell
end if
```

**Comment by askedrelic** [comment] 2016-11-29 11:05
I was just looking at Applescripting for a different reason

All you have is "full title (text, r/o) : Currently active tab track title, if available" thanks to https://github.com/beardedspice/beardedspice/pull/478

```
if application "BeardedSpice" is running then
	tell application "BeardedSpice"
		set test to full title of application "BeardedSpice"
	end tell
end if
```

**Comment by NerdPad** [comment] 2016-11-30 19:28
@askedrelic Thanks. Exactly what I wanted.

**Comment by Porco-Rosso** [comment] 2017-02-17 19:07
@askedrelic Hi, this code recently stopped working, it only returns the site or media player in use, such as "Soundcloud" "Itunes" or "Vox". Do you know if the variable for the title has changed? Is it no longer `full title`?

**Comment by askedrelic** [comment] 2017-02-21 10:00
@Porco-Rosso I can confirm this behavior has changed; applescript only returns the current App name instead of track info.

 Best guess is v2.2.0 changed this, I'm guessing something like how the app is using "displayName" now from this commit https://github.com/beardedspice/beardedspice/commit/c06b6d932df81449e8d32f25efa7c395900e0e22

I would file a new bug/ticket for changing this, I don't have time to look further, but maybe someone else does.

**Comment by Porco-Rosso** [comment] 2017-02-21 18:08
Thanks for replying, I suspected the same.
I was hoping it might be as simple as requesting a different variable in the script.
I've posted in the API thread about this.

**Comment by nerdpad** [comment] 2017-02-21 18:46
I am reopening this issue, as I need a solution for this also.

**Comment by 1ps0** [comment] 2017-02-21 18:48
It wasn't an intentional change. I'm in the process of assembling a patch `v2.2.1` and will try to address this at the same time.

**Comment by nerdpad** [comment] 2017-02-21 18:54
@1ps0 Thank you.

**Comment by 1ps0** [comment] 2017-02-27 04:53
Looks like a small oversight in `BSAppleScriptSupport.m`. I have a couple other small tweaks, but if they take too long I'll just push this one fix.

**Comment by 1ps0** [comment] 2017-03-05 01:23
Pushed `2.2.1`, let me know if it does/doesn't fix your issue. I'm closing the thread, but you should still be able to respond. Thanks :)

**Closed by 1ps0** 2017-03-05 01:23 UTC
Labels: bug

**Comment by Porco-Rosso** [comment] 2017-03-05 11:08
Thanks @1ps0. 
I can confirm it is now working for content from a browser tab. 
However, when playing from iTunes or Vox, it only displays "iTunes" or "Vox", with no track info.

Either way thanks for the effort, I can start making use of this feature already 👍

**Comment by Porco-Rosso** [comment] 2017-03-05 11:51
For now I'm using this hacked together script, in modification of nerdpad's original, but it would be much easier and cleaner to just pull thin information straight from BeardedSpice. Not to mention this script starts to break when multiple players are open.

````AppleScript
(* Get the current song from iTunes or VOX or BeardedSpice *)
if application "iTunes" is running then
	tell application "iTunes"
		try
			set whatshappening to (get player state as string)
		end try
		if whatshappening ≠ "paused" then
			tell application "iTunes"
				if exists current track then
					set theName to the name of the current track
					set theArtist to the artist of the current track
					try
						return theName & " - " & theArtist
					on error err
					end try
				end if
			end tell
		end if
	end tell
else if application "VOX" is running then
	tell application "VOX"
		try
			set state to player state
		end try
		if player state ≠ 0 then
			tell application "VOX"
				
				set theName to track
				set theArtist to artist
				try
					return theName & " - " & theArtist
				on error err
				end try
			end tell
		end if
	end tell
else if application "BeardedSpice" is running then
	tell application "BeardedSpice"
		set title to full title of application "BeardedSpice"
		
		if title is not missing value and title does not start with "Your stream on" then
			try
				return title
			on error err
			end try
		end if
	end tell
end if````

**Comment by 1ps0** [comment] 2017-03-05 19:50
@Porco-Rosso Did it work with iTunes/Vox before `2.2.0`?

**Comment by Porco-Rosso** [comment] 2017-03-05 20:08
I can confirm that [v2.1.3](https://github.com/beardedspice/beardedspice/tree/v2.1.3) Indeed displays the track and artist when calling `full title` in both iTunes and Vox

**Comment by 1ps0** [comment] 2017-03-05 21:18
Le sigh. I'll take a look. Thanks for keeping me aware of all this. It's not normally something I'd use/test.

**Comment by Porco-Rosso** [comment] 2017-03-05 21:22
Sorry about keeping this open, I'll try to take a look and spot the commit where things changed.
