### ISSUE TITLE
Not Working on Safari

### ISSUE THREAD

**Issue by ksherman777** [beardedspice/beardedspice#645] opened 2017-05-08 03:18 UTC
Hi, so I don't know if this is something I did or not, but none of the releases of beardedspice seem compatible with safari on my computer. I currently have 2.2.1 on my mac, running macos 10.12.4. However, I have safari stand installed and to do that I had to trick it into thinking it was Safari 10.0.1, even though it isn't. Obviously I really don't know what I'm doing, but just followed some tutorial on how to get safari stand to work on my computer. Anyways, any advice on how to get beardedspice working with youtube, etc. on safari?

**Comment by 1ps0** [comment] 2017-05-08 03:29
I put together a [quick troubleshooting FAQ](https://github.com/beardedspice/beardedspice/wiki/Troubleshooting). Give it a shot.

**Comment by ksherman777** [comment] 2017-05-22 02:53
Thank you for putting that together. Unfortunately, even after trying all those suggestions it is still not working with Safari for me. I have just updated to 2.2.2 but still nothing. Could it be due to my "older version" of Safari (at least my computer thinks its the older version although it really isn't)?

**Comment by 1ps0** [comment] 2017-05-22 19:12
@ksherman777  Since you're technically not using vanilla Safari, theres a good chance the application itself doesnt support our method of control. 

A quick way to test would be to open up the Terminal application, and run the following command (it tests if the app is responsive to the scripting bridge). If you run the app under a different filename than `Safari.app` just replace it. Should be straightforward.
> sdef /Applications/Safari.app | sdp -fh --basename Safari

If you get a file from it (e.g Safari.h) in the same folder, can you throw it into a gist (https://gist.github.com/) and link it here? My expectation is because its a different application, the adapter we made for Safari vanilla doesn't line up with Safari Stand.

**Comment by 1ps0** [comment] 2017-06-18 22:50
Closing this unless further information is available. Please check with the v2.2.3 release before reopening.

**Closed by 1ps0** 2017-06-18 22:50 UTC

**Comment by mistadikay** [comment] 2017-07-22 12:16
Reproducible with `v2.2.3` with the latest macOS update (`10.12.6`) and Safari `10.1.2 (12603.3.8)`. Tried `v2.2.2` as well — the issue persists there. Tried troubleshooting mentioned above.

When trying
> sdef /Applications/Safari.app | sdp -fh --basename Safari
I get:
```
sdp: warning: parameter "as" of command "save" refers to undefined type 'saveable file format'; assuming type 'id'.
```

**Comment by sschloesser** [comment] 2017-12-03 19:09
I am also getting this issue and the same output when running the command on 10.13.1. Chrome is working just fine tho!

**Comment by Michielskilian** [comment] 2018-08-10 09:18
Same issue with Safari `12.0 (14606.1.32)` on MacOS `10.14 Beta (18A353d)`.

**Comment by rayj-pgi** [comment] 2018-09-20 06:13
this worked: https://github.com/beardedspice/beardedspice/wiki/Wont-Work-issue-after-Safari-Update-(9.1.1-and-later)
