### ISSUE TITLE
Spotify web player updates

### ISSUE THREAD

**Issue by stami** [beardedspice/beardedspice#598] opened 2017-03-01 11:04 UTC
Hi!
Spotify refreshed their web player lately and Beardedspice hasn't worked since.

I tried to update the strategy but I couldn't get the Spotify browser tab to appear in Beardedspice. It just says No applicable tabs open.

Here is my updated strategy file. I tested the functionality in browser's (Chrome) console.

``` javascript
BSStrategy = {
  version:2,
  displayName:"Spotify",
  accepts: {
    method: "predicateOnTab",
    format:"%K LIKE[c] '*spotify.com*'", // open.spotify.com or play.spotify.com
    args: ["URL"]
  },
  isPlaying:function() { document.querySelector('.spoticon-play-32'); },
  toggle: function () {
    if (this.isPlaying()) {
      document.querySelector('.spoticon-pause-32').click();
    } else {
      document.querySelector('.spoticon-play-32').click();
    }
  },
  next: function () { document.querySelector('.spoticon-skip-forward-24').click(); },
  favorite: function () {},
  previous: function () { document.querySelector('.spoticon-skip-back-24').click(); },
  pause:function () {
    if (this.isPlaying()) {
      document.querySelector('.spoticon-pause-32').click();
    }
  },
  trackInfo: function () {}
}
```

**Comment by 1ps0** [comment] 2017-03-01 21:26
@stami This is great! :tada: 
BTW, You can test it in BeardedSpice itself using the `import` button at the bottom of General preferences. 
If that still works feel free to fork/branch/make a pull request and get your new code into the app. Just make sure to update the `versions.plist` entry for `Spotify` to be `2`.

**Comment by stami** [comment] 2017-03-02 05:39
Well, I did try importing and building with updated strategy (updated also `version.plist`) but couldn't get the Spotify tab in Chrome recognized in Beardedspice.

Hmm... Now as I installed Flash and tested on Safari, I get the _old_ web player and Beardedspice recognizes it correctly and works with the _old_ strategy.

It just leaves me wondering why I get different website for the [same url](https://open.spotify.com/browse/featured) and why Spotify tab stopped being recognized on Chrome... If I change the strategy format to be `"%K LIKE[c] '*spotify.com*'"`, it recognizes Spotify home page `www.spotify.com` but not the player page `open.spotify.com`. I guess there is some url manipulation done in the player site so Beardedspice don't get the same url as I see on the browser...

**Comment by 1ps0** [comment] 2017-03-04 23:42
You might be conflicting with another strategy. The more generic you make the URL comparison the greater chance of conflict (since `*` means "everything up to `spotify`). Doing `*.spotify.com` might have a vastly different effect. I'll play with it on my end too and see where we can go with it.

**Comment by bkroggel** [comment] 2017-03-05 10:34
Not sure if I interpret the message in the right way, however taking a look at the Chrome Console while activating BeardedSpice presents the following error message:

```
Refused to execute JavaScript URL because it violates the following Content Security Policy
directive: "script-src 'self' 'unsafe-eval' open.scdn.co www.google-analytics.com cdn.ravenjs.com".
Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable
inline execution.

```

It looks like the whole script gets rejected so although the URL matches probably work the overall magic isn't allowed to happen.

**Comment by 1ps0** [comment] 2017-03-05 21:20
@bkroggel is this only on Spotify web player?

**Comment by bkroggel** [comment] 2017-03-05 22:42
@1ps0 I just double checked it with youtube, vimeo, soundcloud and pocketcast. No issues with these platform so far - BeardedSpice works like a charm and I can't see any related issues on the chrome console. So - as far as I can tell - yes, this issue is just repeatable on Spotify Webplayer and every other website I am using works pretty much fine.

**Comment by AAverin** [comment] 2017-05-04 17:08
Just tried latest version and Spotify webplayer doesn't seem to work still

**Comment by 1ps0** [comment] 2017-05-05 06:23
@AAverin @bkroggel if you could take a look at https://github.com/beardedspice/beardedspice/releases/tag/v2.2.2-b1, I addressed your issues as directly as I could. Just a confirm back that it works and perhaps your OSX/Chrome versions as verifications I didnt miss a test case. I'll put it live production if its stable.

Cheers.

**Comment by bkroggel** [comment] 2017-05-05 09:39
Well done @1ps0. I can confirm it works for the following setting:

- Beardedspice: v2.2.2.-b1
- OS: MacOS Sierra 10.12.4
- Browser: Google Chrome 58.0.3029.96 (64-bit) [stable]
- Strategies (which I tested and therefor can confirm it works):
  - Spotify Web Player
  - Youtube
  - PocketCasts
  - Vimeo
  - Bandcamp

So far I haven't found any issues with the pre-release version - so it looks like the previous issues are all solved.

Great job! :thumbsup:

**Comment by AAverin** [comment] 2017-05-05 09:50
Spotify works fine on 2.2.2-b1, thanks

**Comment by 1ps0** [comment] 2017-05-20 01:43
Closing this in response to release of v2.2.2 officially.

**Closed by 1ps0** 2017-05-20 01:43 UTC
Labels: app support
