### ISSUE TITLE
[App Support] Radiant Player

### ISSUE THREAD

**Issue by ggrelet** [beardedspice/beardedspice#298] opened 2015-12-13 22:09 UTC
Hello
I loooooove your work
I use bearded spice all the time

I also use the app Radiant Player

Could you add the support of this app ? Or tell me how to do so ?

Best regards and keep up the good work !

**Comment by matthewdias** [comment] 2016-02-04 10:33
dupe of #109

**Closed** 2016-05-05 12:56 UTC
Labels: duplicate
