### ISSUE TITLE
quicktime support

### ISSUE THREAD

**Issue by ctf0** [beardedspice/beardedspice#386] opened 2016-04-20 12:51 UTC
right now if BS is running, the control button doesnt work with quick time, 

same with itunes but its a bit tricky because if itunes is already running then the control would work normally whether BS is active or not, but if itunes is closed the media control have no effect because BS is overriding those keys .

**Comment by 1ps0** [comment] 2016-05-05 12:17
Duplicate of #376

**Closed by 1ps0** 2016-05-05 12:17 UTC
Labels: duplicate
