### ISSUE TITLE
(Bug) Keyboard Shortcuts Play/Pause

### ISSUE THREAD

**Issue by kvonspiczak** [beardedspice/beardedspice#259] opened 2015-10-20 08:47 UTC
Hi guys,

since version 1.2 I can not get my media keys of the iMac keyboard to work. I'm talking about the Play/Pause or F8-Button. Whenever I open the preferences and try to set it as default Play/Pause Button it doesn't recognize a button press input.

**Comment by sergiotudela** [comment] 2015-10-23 10:26
The same for here guys, my OSX version `10.11.1 (15B42)`.

**Comment by andr3wk** [comment] 2015-10-23 20:54
Same, media keys don't work in OS X version `10.10.5` and Chrome version `46.0.2490.71`. Seems to be across all sites, but I specifically had issues with Youtube and Vimeo.

**Comment by CaptainYouz** [comment] 2015-10-25 06:55
Same for me.  OS X 10.10.5 (14F1021), Chrome version Version 46.0.2490.71 (64-bit).
Youtube don't work at all for me.

**Comment by Stillness-2** [comment] 2015-10-25 07:53
Duplicate of #257

**Closed by Stillness-2** 2015-10-25 07:53 UTC
