### ISSUE TITLE
[Browser Request] Support for Opera

### ISSUE THREAD

**Issue by plasmoctopus** [beardedspice/beardedspice#396] opened 2016-05-12 17:39 UTC
Would it be possible to also support Opera? Are there big difference for implementation to Chrome, since Opera ist basically Chrome with a different UI?

**Comment by Coder-256** [comment] 2016-05-14 11:46
This is a duplicate of #96, 300 issues back! I'm surprised nobody has implemented this yet. I'll look into it...

**Comment by plasmoctopus** [comment] 2016-05-14 17:19
Oh wow. I’m sorry the search didn’t turn anything up (probably my fault).
Thank you!

**Comment by 1ps0** [comment] 2016-05-15 16:00
Closing this as dupe. It's been referenced in #96 just incase :)

**Closed** 2016-05-15 16:00 UTC
Labels: app support, duplicate
